
alias 09='echo 0123456789'
alias 90='echo 9876543210'

alias AZ='echo ABCDEFGHIJKLMNOPQRSTUVWXYZ'
alias ZA='echo ZYXWVUTSRQPONMLKJIHGFEDCBA'
alias az='echo abcdefghijklmnopqrstuvwxyz'
alias za='echo zyxwvutsrqponmlkjihgfedcba'

alias АЯ='echo АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'
alias ЯА='echo ЯЮЭЬЫЪЩШЧЦХФУТСРПОНМЛКЙИЗЖЁЕДГВБА'
alias ая='echo абвгдеёжзийклмнопрстуфхцчшщъыьэюя'
alias яа='echo яюэьыъщшчцхфутсрпонмлкйизжёедгвба'

function -AZ {
	echo 'A                         '
	echo ' B                        '
	echo '  C                       '
	echo '   D                      '
	echo '    E                     '
	echo '     F                    '
	echo '      G                   '
	echo '       H                  '
	echo '        I                 '
	echo '         J                '
	echo '          K               '
	echo '           L              '
	echo '            M             '
	echo '             N            '
	echo '              O           '
	echo '               P          '
	echo '                Q         '
	echo '                 R        '
	echo '                  S       '
	echo '                   T      '
	echo '                    U     '
	echo '                     V    '
	echo '                      W   '
	echo '                       X  '
	echo '                        Y '
	echo '                         Z'
}

function -ZA {
	echo 'Z                         '
	echo ' Y                        '
	echo '  X                       '
	echo '   W                      '
	echo '    V                     '
	echo '     U                    '
	echo '      T                   '
	echo '       S                  '
	echo '        R                 '
	echo '         Q                '
	echo '          P               '
	echo '           O              '
	echo '            N             '
	echo '             M            '
	echo '              L           '
	echo '               K          '
	echo '                J         '
	echo '                 I        '
	echo '                  H       '
	echo '                   G      '
	echo '                    F     '
	echo '                     E    '
	echo '                      D   '
	echo '                       C  '
	echo '                        B '
	echo '                         A'
}

function -az {
	echo 'a                         '
	echo ' b                        '
	echo '  c                       '
	echo '   d                      '
	echo '    e                     '
	echo '     f                    '
	echo '      g                   '
	echo '       h                  '
	echo '        i                 '
	echo '         j                '
	echo '          k               '
	echo '           l              '
	echo '            m             '
	echo '             n            '
	echo '              o           '
	echo '               p          '
	echo '                q         '
	echo '                 r        '
	echo '                  s       '
	echo '                   t      '
	echo '                    u     '
	echo '                     v    '
	echo '                      w   '
	echo '                       x  '
	echo '                        y '
	echo '                         z'
}

function -za {
	echo 'z                         '
	echo ' y                        '
	echo '  x                       '
	echo '   w                      '
	echo '    v                     '
	echo '     u                    '
	echo '      t                   '
	echo '       s                  '
	echo '        r                 '
	echo '         q                '
	echo '          p               '
	echo '           o              '
	echo '            n             '
	echo '             m            '
	echo '              l           '
	echo '               k          '
	echo '                j         '
	echo '                 i        '
	echo '                  h       '
	echo '                   g      '
	echo '                    f     '
	echo '                     e    '
	echo '                      d   '
	echo '                       c  '
	echo '                        b '
	echo '                         a'
}
