
function AZ {
	echo ABCDEFGHIJKLMNOPQRSTUVWXYZ
	echo BBCDEFGHIJKLMNOPQRSTUVWXYZ
	echo CCCDEFGHIJKLMNOPQRSTUVWXYZ
	echo DDDDEFGHIJKLMNOPQRSTUVWXYZ
	echo EEEEEFGHIJKLMNOPQRSTUVWXYZ
	echo FFFFFFGHIJKLMNOPQRSTUVWXYZ
	echo GGGGGGGHIJKLMNOPQRSTUVWXYZ
	echo HHHHHHHHIJKLMNOPQRSTUVWXYZ
	echo IIIIIIIIIJKLMNOPQRSTUVWXYZ
	echo JJJJJJJJJJKLMNOPQRSTUVWXYZ
	echo KKKKKKKKKKKLMNOPQRSTUVWXYZ
	echo LLLLLLLLLLLLMNOPQRSTUVWXYZ
	echo MMMMMMMMMMMMMNOPQRSTUVWXYZ
	echo NNNNNNNNNNNNNNOPQRSTUVWXYZ
	echo OOOOOOOOOOOOOOOPQRSTUVWXYZ
	echo PPPPPPPPPPPPPPPPQRSTUVWXYZ
	echo QQQQQQQQQQQQQQQQQRSTUVWXYZ
	echo RRRRRRRRRRRRRRRRRRSTUVWXYZ
	echo SSSSSSSSSSSSSSSSSSSTUVWXYZ
	echo TTTTTTTTTTTTTTTTTTTTUVWXYZ
	echo UUUUUUUUUUUUUUUUUUUUUVWXYZ
	echo VVVVVVVVVVVVVVVVVVVVVVWXYZ
	echo WWWWWWWWWWWWWWWWWWWWWWWXYZ
	echo XXXXXXXXXXXXXXXXXXXXXXXXYZ
	echo YYYYYYYYYYYYYYYYYYYYYYYYYZ
	echo ZZZZZZZZZZZZZZZZZZZZZZZZZZ
}

function ZA {
	echo ZYXWVUTSRQPONMLKJIHGFEDCBA
	echo YYXWVUTSRQPONMLKJIHGFEDCBA
	echo XXXWVUTSRQPONMLKJIHGFEDCBA
	echo WWWWVUTSRQPONMLKJIHGFEDCBA
	echo VVVVVUTSRQPONMLKJIHGFEDCBA
	echo UUUUUUTSRQPONMLKJIHGFEDCBA
	echo TTTTTTTSRQPONMLKJIHGFEDCBA
	echo SSSSSSSSRQPONMLKJIHGFEDCBA
	echo RRRRRRRRRQPONMLKJIHGFEDCBA
	echo QQQQQQQQQQPONMLKJIHGFEDCBA
	echo PPPPPPPPPPPONMLKJIHGFEDCBA
	echo OOOOOOOOOOOONMLKJIHGFEDCBA
	echo NNNNNNNNNNNNNMLKJIHGFEDCBA
	echo MMMMMMMMMMMMMMLKJIHGFEDCBA
	echo LLLLLLLLLLLLLLLKJIHGFEDCBA
	echo KKKKKKKKKKKKKKKKJIHGFEDCBA
	echo JJJJJJJJJJJJJJJJJIHGFEDCBA
	echo IIIIIIIIIIIIIIIIIIHGFEDCBA
	echo HHHHHHHHHHHHHHHHHHHGFEDCBA
	echo GGGGGGGGGGGGGGGGGGGGFEDCBA
	echo FFFFFFFFFFFFFFFFFFFFFEDCBA
	echo EEEEEEEEEEEEEEEEEEEEEEDCBA
	echo DDDDDDDDDDDDDDDDDDDDDDDCBA
	echo CCCCCCCCCCCCCCCCCCCCCCCCBA
	echo BBBBBBBBBBBBBBBBBBBBBBBBBA
	echo AAAAAAAAAAAAAAAAAAAAAAAAAA
}

function az {
	echo abcdefghijklmnopqrstuvwxyz
	echo bbcdefghijklmnopqrstuvwxyz
	echo cccdefghijklmnopqrstuvwxyz
	echo ddddefghijklmnopqrstuvwxyz
	echo eeeeefghijklmnopqrstuvwxyz
	echo ffffffghijklmnopqrstuvwxyz
	echo ggggggghijklmnopqrstuvwxyz
	echo hhhhhhhhijklmnopqrstuvwxyz
	echo iiiiiiiiijklmnopqrstuvwxyz
	echo jjjjjjjjjjklmnopqrstuvwxyz
	echo kkkkkkkkkkklmnopqrstuvwxyz
	echo llllllllllllmnopqrstuvwxyz
	echo mmmmmmmmmmmmmnopqrstuvwxyz
	echo nnnnnnnnnnnnnnopqrstuvwxyz
	echo ooooooooooooooopqrstuvwxyz
	echo ppppppppppppppppqrstuvwxyz
	echo qqqqqqqqqqqqqqqqqrstuvwxyz
	echo rrrrrrrrrrrrrrrrrrstuvwxyz
	echo ssssssssssssssssssstuvwxyz
	echo ttttttttttttttttttttuvwxyz
	echo uuuuuuuuuuuuuuuuuuuuuvwxyz
	echo vvvvvvvvvvvvvvvvvvvvvvwxyz
	echo wwwwwwwwwwwwwwwwwwwwwwwxyz
	echo xxxxxxxxxxxxxxxxxxxxxxxxyz
	echo yyyyyyyyyyyyyyyyyyyyyyyyyz
	echo zzzzzzzzzzzzzzzzzzzzzzzzzz
}

function za {
	echo zyxwvutsrqponmlkjihgfedcba
	echo yyxwvutsrqponmlkjihgfedcba
	echo xxxwvutsrqponmlkjihgfedcba
	echo wwwwvutsrqponmlkjihgfedcba
	echo vvvvvutsrqponmlkjihgfedcba
	echo uuuuuutsrqponmlkjihgfedcba
	echo tttttttsrqponmlkjihgfedcba
	echo ssssssssrqponmlkjihgfedcba
	echo rrrrrrrrrqponmlkjihgfedcba
	echo qqqqqqqqqqponmlkjihgfedcba
	echo ppppppppppponmlkjihgfedcba
	echo oooooooooooonmlkjihgfedcba
	echo nnnnnnnnnnnnnmlkjihgfedcba
	echo mmmmmmmmmmmmmmlkjihgfedcba
	echo lllllllllllllllkjihgfedcba
	echo kkkkkkkkkkkkkkkkjihgfedcba
	echo jjjjjjjjjjjjjjjjjihgfedcba
	echo iiiiiiiiiiiiiiiiiihgfedcba
	echo hhhhhhhhhhhhhhhhhhhgfedcba
	echo ggggggggggggggggggggfedcba
	echo fffffffffffffffffffffedcba
	echo eeeeeeeeeeeeeeeeeeeeeedcba
	echo dddddddddddddddddddddddcba
	echo ccccccccccccccccccccccccba
	echo bbbbbbbbbbbbbbbbbbbbbbbbba
	echo aaaaaaaaaaaaaaaaaaaaaaaaaa
}
